# Site wide configuration

title: μ„Έν›
locale: en_US
description: Dev Blog
logo: site-logo.png
search: true
share : true
url: https://brosbj.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true



# Enter your Facebook app-code
facebook_user_id: brosbj
facebook_app_id: 1182543191810574


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: μ„Έν›
  avatar: bio-photo.jpg
  email: brosbj@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: brosbj
  github: brosbj
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: brosbj
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-80659403-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
